changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions
  categories:
    - title: "âœ¨ Fitur Baru"
      labels:
        - "feature"
        - "enhancement"
      commits:
        - "feat"
    - title: "ğŸ› Perbaikan Bug"
      labels:
        - "bug"
      commits:
        - "fix"
    - title: "ğŸ”¨ Refactoring & Peningkatan Kode"
      labels:
        - "refactor"
      commits:
        - "refactor"
    - title: "ğŸ“„ Dokumentasi"
      labels:
        - "documentation"
      commits:
        - "docs"
    - title: "âš™ï¸ Lain-lain"
      labels:
        - "*"